openapi: "3.0.0"
info:
  title: InfluxUI Unification API Service
  version: 0.1.0
servers:
  - url: /api/experimental
paths:
  "/orgs/{orgID}/users/{userID}":
    delete:
      operationId: DeleteOrgsIDCloudUserID
      tags:
        - CloudUsers
        - Organizations
      summary: Deletes a cloud user
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: userID
          schema:
            type: string
          required: true
          description: The ID of the user to remove.
        - in: path
          name: orgID
          schema:
            type: string
          required: true
          description: The organization ID.
      responses:
        "204":
          description: User removed
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/orgs/{orgID}/users":
    get:
      operationId: GetCloudUsers
      tags:
        - CloudUsers
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: orgID
          description: Specifies the organization ID of the CloudUser.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of cloud users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CloudUsers"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/orgs/{orgID}/invites":
    post:
      operationId: PostOrgsIDInvites
      tags:
        - Invites
        - Organizations
      summary: Creates an invite to an organization
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: orgID
          schema:
            type: string
          required: true
          description: The organization ID.
      requestBody:
        description: Invite to be sent
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Invite"
      responses:
        "201":
          description: Invite sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Invite"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/orgs/{orgID}/invites/{inviteID}":
    delete:
      operationId: DeleteOrgsIDInviteID
      tags:
        - Invites
        - Organizations
      summary: Remove an invite to an organization
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: inviteID
          schema:
            type: string
          required: true
          description: The ID of the invite to remove.
        - in: path
          name: orgID
          schema:
            type: string
          required: true
          description: The organization ID.
      responses:
        "204":
          description: Invite removed
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/orgs/{orgID}/invites/{inviteID}/resend":
    post:
      operationId: DeleteOrgsIDInviteID
      tags:
        - Invites
        - Organizations
      summary: Resends an invite
      parameters:
        - $ref: "#/components/parameters/TraceSpan"
        - in: path
          name: inviteID
          schema:
            type: string
          required: true
          description: The ID of the invite to resend.
        - in: path
          name: orgID
          schema:
            type: string
          required: true
          description: The organization ID.
      responses:
        "200":
          description: Invite resent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Invite"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
parameters:
components:
  parameters:
    TraceSpan:
      $ref: "./swagger.yml#/components/parameters/TraceSpan"
  schemas:
    Error:
      $ref: "./swagger.yml#/components/schemas/Error"
    CloudUser:
      properties:
        id:
          description: the idpe id of the user
          readOnly: true
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - member
            - owner
        links:
          type: object
          readOnly: true
          example:
            self: "/api/v2/cloud_users/1"
          properties:
            self:
              type: string
              format: uri
      required: [id, email, role]
    CloudUsers:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
        users:
          type: array
          items:
            $ref: "#/components/schemas/CloudUser"
    Invite:
      properties:
        id:
          description: the idpe id of the invite
          readOnly: true
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - member
            - owner
        expiresAt:
          format: date-time
          type: string
        links:
          type: object
          readOnly: true
          example:
            self: "/api/v2/invites/1"
          properties:
            self:
              type: string
              format: uri
      required: [id, email, role]
    Invites:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
        invites:
          type: array
          items:
            $ref: "#/components/schemas/Invite"
